name: Deploy

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy to Crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable && rustup default stable

      - name: Deploy
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO }}
          ignore-unpublished-changes: true
          no-verify: true
